LapTimes/Areas/ManageRacers/Controllers/HomeController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using LapTimes.Models;

namespace LapTimes.Areas.ManageRacers.Controllers
{
    public class HomeController : Controller
    {
      private LapTimesContext db = new LapTimesContext();

      //
      // GET: /ManageRacers/Home/

      public ActionResult Index()
      {
        ViewBag.ClassId = new SelectList(db.ClassNames.OrderBy(c => c.Name), "ClassId", "Name");
        ViewBag.LeagueId = new SelectList(db.Leagues, "LeagueId", "Name");
        ViewBag.AtLeastTwoRacers = db.Racers.Where(r => r.IsWaitingForRace).Take(2).Count() == 2;

        return View(new Racer{RacerId = 0});
      }

      [HttpPost]
      public ActionResult Index(Racer racer)
      {
        if (racer.RacerId == 0)
        {
          if (ModelState.IsValid)
          {
            racer.IsWaitingForRace = true;
            db.Racers.Add(racer);
            db.SaveChanges();
            return RedirectToAction("Index");
          }

          ViewBag.ClassId = new SelectList(db.ClassNames.OrderBy(c => c.Name), "ClassId", "Name", racer.ClassId);
          ViewBag.LeagueId = new SelectList(db.Leagues, "LeagueId", "Name", racer.LeagueId);
          return View(racer);
        }

        Racer foundRacer = db.Racers.Find(racer.RacerId);

        foundRacer.LeagueId = racer.LeagueId;
        foundRacer.ClassId = racer.ClassId;

        foundRacer.IsWaitingForRace = true;
        db.Entry(foundRacer).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
    }
}

LapTimes/Areas/ManageRaces/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LapTimes.Models;

namespace LapTimes.Areas.ManageRaces.Controllers
{
    public class CarsController : Controller
    {
        private LapTimesContext db = new LapTimesContext();

        //
        // GET: /ManageRaces/Cars/

        public ActionResult Index()
        {
            return View(db.Cars.ToList());
        }

        //
        // GET: /ManageRaces/Cars/Details/5

        public ActionResult Details(int id = 0)
        {
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //
        // GET: /ManageRaces/Cars/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ManageRaces/Cars/Create

        [HttpPost]
        public ActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        //
        // GET: /ManageRaces/Cars/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //
        // POST: /ManageRaces/Cars/Edit/5

        [HttpPost]
        public ActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        //
        // GET: /ManageRaces/Cars/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //
        // POST: /ManageRaces/Cars/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LapTimes/Areas/ManageRaces/Controllers/HomeController.cs
using System.Data;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Configuration;
using System.Web.Mvc;
using LapTimes.Models;

namespace LapTimes.Areas.ManageRaces.Controllers
{
    public class HomeController : Controller
    {
      private readonly LapTimesContext _db = new LapTimesContext();
      private readonly ILapTimeRepository _repo;

      public HomeController(): this(new LapTimeRepository())
      {}

      public HomeController(ILapTimeRepository repo)
      {
        _repo = repo;
      }

      private readonly int _numberOfLanes = int.Parse(WebConfigurationManager.AppSettings["RaceLanes"]);
      
      //
      // GET: /ManageRaces/Home/

      public ActionResult Index()
      {
        ViewBag.NumberOfLanes = _numberOfLanes;
        ViewBag.CarId = new SelectList(_db.Cars.OrderBy(c => c.CarId), "CarId", "Name");
        var racers = getFormattedRacers().ToList();
        ViewBag.RacerId = new SelectList(racers, "RacerId", "Name");

        if (racers.Any() && racers.Take(2).Count() == 2)
        {
          // There are at least two racers waiting
          var currentRace = _repo.CurrentRace() ??
                            new Race
                              {
                                RaceId = 0,
                                Drivers =
                                  new List<CurrentDriver>(_numberOfLanes)
                              };

          if (currentRace.RaceId == 0)
          {
            for (int lane = 0; lane < _numberOfLanes; lane++)
            {
              currentRace.Drivers.Add(new CurrentDriver {Lane = lane + 1});
            }
          }

          return View(currentRace);
        }

        return RedirectToAction("Index", "Home", new {Area = "ManageRacers"});
      }

      [HttpPost]
      public ActionResult Index(Race newRace)
      {
        if (ModelState.IsValid)
        {
          _db.Races.Add(newRace);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }

        ViewBag.CarId = new SelectList(_db.Cars.OrderBy(c => c.CarId), "CarId", "Name");

        ViewBag.RacerId =
          new SelectList(getFormattedRacers(),
            "RacerId",
            "Name");

        return View(newRace);
      }

      private IEnumerable<FormattedRacer> getFormattedRacers()
      {
        return _db.Racers.Include(r => r.ClassName)
          .Where(r => r.IsWaitingForRace)
          .OrderBy(r => r.Name)
          .AsEnumerable()
          .Select(r => new FormattedRacer{RacerId = r.RacerId, Name = string.Format("{0} - {1}", r.Name, r.ClassName.Name)});
      }
    }

  public class FormattedRacer
  {
    public int RacerId { get; set; }
    public string Name { get; set; }
  }
}

LapTimes/Areas/ManageRaces/Controllers/RacesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using LapTimes.Models;

namespace LapTimes.Areas.ManageRaces.Controllers
{
  public class RacesController : Controller
  {
    private readonly LapTimesContext _db = new LapTimesContext();

    private readonly ILapTimeRepository _repo;

    public RacesController(): this(new LapTimeRepository())
    {}

    public RacesController(ILapTimeRepository repo)
    {
      _repo = repo;
    }

    //
    // GET: /ManageRaces/Races/

    public ActionResult Index()
    {
      return View(_db.Races.Include(r => r.Drivers).Include("Drivers.Racer").Include("Drivers.Car").ToList());
    }

    //
    // GET: /ManageRaces/Races/Details/5

    public ActionResult Details(int id = 0)
    {
      Race race = _repo.GetRace(id);

      if (race == null)
      {
        return HttpNotFound();
      }

      return View(race);
    }

    //
    // GET: /ManageRaces/Races/Edit/5

    public ActionResult Edit(int id = 0)
    {
      Race race = _repo.GetRace(id);

      if (race == null)
      {
        return HttpNotFound();
      }
      
      return View(race);
    }

    //
    // POST: /ManageRaces/Races/Edit/5

    [HttpPost]
    public ActionResult Edit(Race race)
    {
      if (ModelState.IsValid)
      {
        _db.Entry(race).State = EntityState.Modified;
        _db.SaveChanges();

        return RedirectToAction("Index");
      }

      return View(race);
    }

    //
    // GET: /ManageRaces/Races/Delete/5

    public ActionResult Delete(int id = 0)
    {
      Race race = _repo.GetRace(id);

      if (race == null)
      {
        return HttpNotFound();
      }
      
      return View(race);
    }

    //
    // POST: /ManageRaces/Races/Delete/5

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      _repo.DeleteRace(id);

      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
      _db.Dispose();
      base.Dispose(disposing);
    }
  }
}

LapTimes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LapTimes.Models;

namespace LapTimes.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILapTimeRepository _lapRepo;

    public HomeController(): this (new LapTimeRepository())
    {
    }

    public HomeController(ILapTimeRepository lapRepo)
    {
      _lapRepo = lapRepo;
    }

    public ActionResult Index()
    {
      ViewBag.Message = "Waiting for a race to begin...";

      return View();
    }

    public ActionResult About()
    {
      ViewBag.Message = "Your app description page.";

      return View();
    }

    public ActionResult Contact()
    {
      ViewBag.Message = "Your contact page.";

      return View();
    }
  }
}

LapTimes/Areas/ManageRaces/Views/Home/Index.cshtml
@model LapTimes.Models.Race

@{
  ViewBag.Title = "Manage Races";
}

<hgroup class="title">
  <h1>@ViewBag.Title</h1>
</hgroup>

<article>
  <h2>Run a race</h2>
  @if (Model == null || Model.RaceId == 0)
  {
    using (Html.BeginForm())
    {
      @Html.ValidationSummary(true)

      <fieldset>
        <legend>Run a race</legend>

        @Html.HiddenFor(model => model.RaceId)

        @Html.EditorFor(model => model.Drivers)

        <p>
          <input type="submit" value="Prepare Race" />
        </p>

      </fieldset>
    }
  }
  else
  { 
  <div>
    @Html.HiddenFor(model => model.RaceId)
    <ul class="home-current-racers">
    @for (int i = 0; i < Model.Drivers.Count(); i++)
    {
      <li>
        <i class="fa fa-tachometer"></i> 
        In lane @Html.DisplayFor(model => model.Drivers[i].Lane): 
        <span class="home-driver-name">@Html.DisplayFor(model => model.Drivers[i].Racer.Name)</span> 
        is driving car number <span class="home-car-name">@Html.DisplayFor(model => model.Drivers[i].Car.Name)</span>
      </li>
    }
    </ul>
    <!-- Set up Knockout Stopwatches... -->
    <h3>Time:</h3>

    <input id="rawStopwatch" type="hidden" value="0" />
    <input class="stopwatch" id="stopwatch" type="text" value="00:00.000" /><br/>
    <input class="button" id="startandstopbutton" type="button" value="Start" /><br/>
    <input class="button" id="marklapbutton" type="button" value="10 Laps Complete!" /><br/>
    <input class="button" id="resetbutton" type="button" value="Reset Race" /><br/>
    <ol data-bind="foreach: LaneTimes">
      <li>
        <span class="race-time" data-bind="text: convertTime($data)"></span>
        <input class="race-time" type="text" data-bind="attr: {'data-val': $index}" />
        <select class="finished-times" data-bind="attr: {'data-val': $index}, 
                           options: $root.CurrentRace().Drivers(),
                           optionsText: function (item) {  return item.Lane() + '. ' + item.Name() + ' (' + item.Car() + ')';},
                           optionsValue: 'RacerId'
                           " ></select>
      </li>
    </ol>
    <input type="button" class="button" id="submitTimes" value="Finish Race!" data-bind="visible: LaneTimes().length == numberOfLanes, click: updateTimes"/>
  </div>
  }
</article>

<aside>
  <h3>Race Management:</h3>
  <ul>
    <li>@Html.ActionLink("Manage Races", "Index", "Races")</li>
    <li>@Html.ActionLink("Manage Cars", "Index", "Cars")</li>
  </ul>
</aside>

@section scripts
{
  @Scripts.Render("~/bundles/Knockout")
  <script src="~/signalr/hubs"></script>

  <script>
   var numberOfLanes = @ViewBag.NumberOfLanes;

    $(function () {
      var drivers = $('[id*="RacerId"]');
      var driverOptions = drivers.find('option');
      var cars = $('[id*="CarId"]');

      if (drivers.length > 0) {
        drivers.change(function () {
          var val = $(this).val();

          var selected = [];
          selected.push(val);

          drivers.not($(this)).each(function (i, element) {
            if ($(element).val()) {
              // We have a selected value
              if (selected.indexOf($(element).val()) < 0) {
                // Current item also isn't already selected...
                selected.push($(element).val());
              } else {
                // find option that isn't selected...
                driverOptions.each(function (j, option) {
                  if (selected.indexOf($(option).val()) < 0) {
                    selected.push($(option).val());
                    $(element).val($(option).val());
                  }
                });
              }
            }
          });
        });

        cars.change(function () {
          var val = $(this).val();

          cars.not($(this)).each(function (i, element) {
            if ($(element).val() && $(element).val() == val) {
              $(element).val('');
            }
          });
        });
      }
      else
      {
        var x = new clsStopwatch();
        var rawTime = $('#rawStopwatch');
        var formattedTime = $('#stopwatch');
        var clockTimer;
        var finishedLanes = 0;

        $('#startandstopbutton').click(function(){
          if (!x.isRunning()) {
            vm.RaceStarted();
            clockTimer = setInterval(update, 1);
            x.start();
            $(this).attr('value', 'Stop');
          } else {
            stopTimer(true);
          }
        });

        $('#marklapbutton').click(function(){
          if (x.isRunning()) {
              vm.LaneTimes.push(x.time());
              finishedLanes++;
            if (finishedLanes >= numberOfLanes) {
              stopTimer(false);
            }
          }
        });

        $('#resetbutton').click(function(){
          if (x.isRunning()) {
            stopTimer(true);
          }
          vm.LaneTimes.removeAll();
          finishedLanes = 0;
          x.reset();
          update();
        });

        function update(){
          $(formattedTime).val(convertTime(x.time()));
          $(rawTime).val(x.time());
        }

        function stopTimer(aborted) {
          clockTimer = null;
          x.stop();
          $('#startandstopbutton').attr('value', 'Start');
          vm.RaceStopped(aborted);
        }

        // Set Up Knockout/SignalR for the Races

        function RaceViewModel() {
          var self = this;
          self.CurrentRace = ko.observable();
          self.LaneTimes = ko.observableArray();

          var race = $.connection.raceHub;

          self.updateTimes = function() {
            var laneResults = [];

            for (var i = 0; i < numberOfLanes; i++) {
                var time = $("input[data-val=" + i + "]");
              var racer = $("select[data-val=" + i + "]");
              laneResults.push({ RacerId: $(racer).val(), RaceTime: $(time).val() });
            }

            race.server.finishRaceString(self.CurrentRace().RaceId, laneResults);
          };

          // Initializes the view model
          self.init = function() {
            race.server.getCurrentRace();
          };

          race.client.getCurrentRace = function(currentRace) {
            self.CurrentRace(new CurrentRace(currentRace));
          };

          race.client.RedirectToRace = function() {
            location.reload(true);
          };

          self.RaceStarted = function(){
            race.server.startRace(self.CurrentRace().RaceId);
          };

          self.RaceStopped = function(aborted){
            race.server.stopRace(self.CurrentRace().RaceId, aborted);
          };

        }

        var vm = new RaceViewModel();
        $.connection.hub.start(function () { vm.init(); });

        ko.applyBindings(vm);
      }
    });


 
  </script>
}